import os
import shutil
import tempfile
import git_utils
from git import Repo

def test_push():
    # Setup: Create a "remote" repo (bare)
    remote_dir = tempfile.mkdtemp()
    remote_repo = Repo.init(remote_dir, bare=True)
    print(f"Created bare remote at {remote_dir}")

    # Setup: Create a "source" repo and push initial content to remote
    source_dir = tempfile.mkdtemp()
    source_repo = Repo.init(source_dir)
    # Ensure we are on main
    if 'main' in source_repo.heads:
        source_repo.heads.main.checkout()
    else:
        source_repo.git.checkout('-b', 'main')

    origin = source_repo.create_remote('origin', remote_dir)
    
    readme_path = os.path.join(source_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write("# Initial README")
    
    source_repo.index.add(["README.md"])
    source_repo.index.commit("Initial commit")
    source_repo.git.push("--set-upstream", "origin", "main")
    print("Initialized remote with main branch")

    # Test: Use git_utils.push_file to update README
    new_content = "# Updated README\n\nGenerated by Git Sense"
    print("Attempting to push update via git_utils...")
    
    success, message = git_utils.push_file(
        repo_url=remote_dir, # treating local dir as remote url
        file_path="README.md",
        content=new_content,
        commit_message="Test Update",
        branch_name="main"
    )

    print(f"Push Result: {success} - {message}")

    # Verify: Clone remote again and check content
    check_dir = tempfile.mkdtemp()
    Repo.clone_from(remote_dir, check_dir, branch='main')
    with open(os.path.join(check_dir, "README.md"), "r") as f:
        content = f.read()
    
    print(f"Content in remote: {content}")
    
    if content == new_content:
        print("VERIFICATION SUCCESSFUL")
    else:
        print("VERIFICATION FAILED")

    # Cleanup
    shutil.rmtree(remote_dir)
    shutil.rmtree(source_dir)
    shutil.rmtree(check_dir)

if __name__ == "__main__":
    test_push()
